// This file is automatically generated.
// Please do not change this file!
declare const cssExports: {
  'hyphened-classname': string;
  otherClass: string;
  someClass: string;
  underscored_classname: string;
  validClass: string;
};

export default cssExports;
